# 异步及相关问题

[toc]

## 1.任务队列

>js单线程，由上到下按顺序执行，异步事件放入事件队列中，分为宏任务和微任务，主进程结束完，循环执行事件队列的微任务然后宏任务。
>>**宏任务**有 主进程，setTimeout，setInterval，Ajax，DOM事件；
>>**微任务**有Promise.then，process.nextTick，MutationObserver（h5监听dom变化）

异步任务有了运行结果，将事件放置在任务队列中。宏任务中有微任务，执行完宏任务把微任务放到微任务队列中，所有微任务执行完再执行下一个宏任务开始下一个事件循环

## 2. async、await
```javascript
function anum() {
    return new Promise(function (resolve, reject) {
        let a = 10
        resolve(a)
    })
}
async function anum1() {
    var aa = await anum()
    return aa
}
```
>async的函数内部创建了promise，return则相当于执行了Promise.resolve(aa) 可以用.then接收 async的返回值是个promise

> await只能在async中使用 后面接一个函数（如果是promise(或者async)就等待resolove(或者return)的返回值作为结果再执行下一个函数 如果是普通函数直接执行不需要等待结果）

```javascript
anum1().then(res => {
    console.log(res)
    return new Promise((resolve, reject)=> {
        setTimeout(() => {
            // reject(a)
            resolve(res)
        }, 2000)
    })
}).then(res => {
    // throw 'asd'
    console.log(res);
}).then(res => {
    // throw 'asd'
    return new Promise((resolve, reject) => {
        setTimeout(()=>{
            resolve(22)
        }, 1000)
    })
    console.log(res);
}).then(res => {
    // throw 'asd' 
    console.log(res);
}, err => {
    console.log(err, 8989) // .then的第二个函数 err 优先级要高于.catch，可以监听当前then以上的错误，但是不能监听当前.then 的错误，回调函数根据状态只会执行一次
    throw 'err'
}).catch(err => {
    console.log(err, 9919)
})
```

## 3. Promise
1. Promise 需要注意的哪些
> 1. 通过回调函数的方式定义resolve和reject函数作为参数传递
> 2. 有pending，resolve，reject三个状态，执行回调函数pending状态会改变
> 3. then函数是按顺序立即执行的，每个.then都会直接返回新的promise，promise中的回调函数执行是异步的，通过状态判断直接执行还是放在回调函数队列中，promise中有一个成功和失败的函数队列，根据上一个函数成功或者失败执行对应的函数确定修改当前promise的状态。
> 4. then会判断返回值是否是promise还是普通值，如果是promise就取它的返回值
> 5. .then.catch没有回调函数或者不是函数类型（重新创建回调函数），返回值就是 上一个then函数返回的promise中的两个回调函数(resolve(), reject())执行，改变了当前状态的this.resolve或者this.reject的值
> 6. all，race，any这些函数传的参数如果不是promise，按照成功算，如果有返回就返回这项本身

1. 函数队列主要作用
> 如果promise主函数resolve没有异步，状态改变第一个.then是直接执行，返回promise；
> 如果promise主函数是异步，第一个.then也是放在队列中执行，后续的每一个.then都是放在它当前的也就是上一个.then返回的promise的队列中执行；
> 如果promise多次调用非链式，主函数如果不是异步，多个.then不需要放入队列，下一层需要放入，主函数如果是异步，多个.then都放到当前promise队列中，状态改变再循环执行

```javascript
class newPromise {
    constructor(fn) {
        //三个状态
        this.status = 'pending',
        this.resolve = undefined;
        this.reject = undefined;
        this.resolveCallback = [];
        this.rejectCallback = [];
        let resolve = value => {
            if (this.status === 'pending') {
                // resolve函数如果是一个Promise，需要等待结果
                if(typeof value === 'object' && typeof value.then == 'function') {
                    value.then(res => {
                        this.status = 'fulfilled';
                        this.resolve = res;
                        this.resolveCallback.forEach(fn => { fn() });
                    }, err => {
                        this.status = 'rejected';
                        this.reject = err;
                        this.rejectCallback.forEach(fn => { fn() });
                    })
                } else {
                    this.status = 'fulfilled';
                    this.resolve = value;
                    this.resolveCallback.forEach(fn => { fn() });
                }
            }
        };
        let reject = value => {
            if (this.status === 'pending') {
                this.status = 'rejected';
                this.reject = value;
                this.rejectCallback.forEach(fn => {
                    fn()
                });
            }
        }
        try {
            fn(resolve, reject)
        } catch (e) {
            reject(e)
        }
    }
    then(onResolved, onRejected) {
        // console.log(onRejected, 66, this.status)
        // 注意点6，返回值不是函数或者不存在，直接返回当前状态的this.resolve或者this.reject，下一个.then.catch可以接收到
        onResolved = typeof onResolved === 'function' ? onResolved : res => res;
        // 当前.then没有失败的回调但是后面的.then的失败回调是可以接收到错误信息的，throw后到下面catch执行reject将错误信息回调
        onRejected = typeof onRejected === 'function' ? onRejected : err => {
            throw err
        };
        let promise = new newPromise((resolve, reject) => {
            // peomise没有异步 直接执行
            if (this.status === 'fulfilled') {
                // 模拟微任务mirotask异步执行
                setTimeout(() => {
                    try {
                        // 执行回调函数
                        let r = onResolved(this.resolve);
                        // 判断返回值是否是promise，然后执行resolve和reject回调，返回的promise会执行回调函数执行函数队列，然后再执行resolve。。。。。
                        isPromise(promise, r, resolve, reject);
                    } catch (err) {
                        reject(err);
                    }
                }, 0)
            }
            if (this.status === 'rejected') {
                setTimeout(() => {
                    try {
                        // 不能将this.reject传回去就结束了，可能里面return了值，Promise或者throw，后面的.then.catch还可以接收到，.catch也可以继续return
                        let r = onRejected(this.reject)
                        isPromise(promise, r, resolve, reject);
                    } catch (err) {
                        reject(err);
                    }
                }, 0)
            }
            if (this.status === 'pending') {
                // 函数中避免立即执行
                this.resolveCallback.push(() => {
                    setTimeout(() => {
                        try {
                            // 执行回调函数
                            let r = onResolved(this.resolve);
                            // 判断返回值是否是promise，然后执行resolve和reject回调，返回的promise会执行回调函数执行函数队列，然后再执行resolve。。。。。
                            isPromise(promise, r, resolve, reject);
                        } catch (err) {
                            reject(err)
                        }
                    }, 0)
                })
                this.rejectCallback.push(() => {
                    setTimeout(() => {
                        try {
                            // 执行回调函数
                            let r = onRejected(this.reject);
                            // 判断返回值是否是promise，然后执行resolve和reject回调，返回的promise会执行回调函数执行函数队列，然后再执行resolve。。。。。
                            isPromise(promise, r, resolve, reject);
                        } catch (err) {
                            reject(err)
                        }
                    }, 0)
                })
            }
        })
        return promise
    }
    catch (onRejected) {
        return this.then(null, onRejected);
    }
    finallys(cb) {
        return this.then(cb, cb)
    }
    static resolve(res) {
        return new newPromise((resolve, reject) => {
            resolve(res)
        });
    }
}
function isPromise(promise, r, resolve, reject) {
    if (r === promise) throw ('不能以当前promise作为返回值');
    // 判断返回值是否是promise，如果是promise需要等待promise的返回值再执行resolve改变return的promise状态
    if (r && (typeof r === 'function' || typeof r === 'object')) {
        // 返回函数原型中有.then函数认为是promise
        try {
            if (typeof r.then === 'function') {
                // 如果是promise执行.then获取返回值res判断是否还是promise
                r.then(res => {
                    // console.log(res)
                    isPromise(promise, res, resolve, reject);
                }, err => {
                    // console.log(err)
                    reject(err);
                })
            } else {
                resolve(r);
            }
        } catch (err) {
            reject(err);
        }
    } else {
        // 返回值不是promise直接执行
        resolve(r);
    }
}
```

## 4. Promise.all

>有错误的返回错误的，所有都成功返回值是按循环顺序的结果数组，不是执行顺序 []格式

```javascript
const promiseAll = function(promises) {
    let resolveNum = 0 //记录resolve的条数
    let array = Array.from(promises) //数据的兼容性处理 
    let length = array.length
    let lists = new Array(length)
    return new Promise((resolve, reject) => {
        for (let i = 0; i < length; i++) {
            Promise.resolve(array[i]).then((res) => {
                lists[i] = res
                resolveNum++
                if (resolveNum === length) {
                    resolve(lists)
                }
            }, (err) => {
                reject(err)
            })
        }
    })
}
```

## 5. Promise.allSettled

> 成功和失败都会按循环顺序返回状态和结果数组， [{status: '', value: ''}]格式，没有catch

```javascript
const promiseAllSettled = function(promises) {
    let count = 0 //记录resolve的条数
    let array = Array.from(promises) //数据的兼容性处理 
    let length = array.length
    let lists = new Array(length)
    return new Promise((resolve, reject) => {
        const fn = (i, value, status) => {
            lists[i] = {
                status,
                value
            }
            count++
            if (count === length) {
                resolve(lists)
            }
        }
        for (let i = 0; i < length; i++) {
            Promise.resolve(array[i]).then((res) => {
                fn(i, res, 'fulfilled')
            }, (err) => {
                fn(i, err, 'rejected')
            })
        }
    })
}
```

## 6. Promise.race

> 返回执行最快的，无论成功还是失败

```javascript
const promiseRace = (promises) => {
    return new Promise((resolve, reject) => {
        for (p of promises) {
            // 谁快谁先resolve输出
            console.log(p)
            p.then(resolve, reject) // .then中回调函数会执行
        }
    })
}
```

## 7. Promise.any

>可以理解为和Promise.all相反，有一个成功返回成功结果，或者所有失败则报错 All promises were rejected

```javascript
const promiseAny = (promises) => {
    let count = 0
    let length = promises.length
    let res = new Array(length)
    return new Promise((resolve, reject) => {
        for (let i = 0; i < length; i++) {
            Promise.resolve(promises[i]).then((res) => {
                resolve(res)
            }, (err) => {
                res[i] = err
                count ++
                if (count === length) reject(new AggregateError(res, 'All promises were rejected'))
            })
        }
    })
}
```
